import UserDetail from './user/UserDetail'
import GameCreate from './user/GameCreate'
import GameUser from './user/GameUser'
import Weather from './user/Weather'
import Game from './user/Game'
import GameList from './user/GameList'
import GameDetail from './user/GameDetail'
import UserList from './user/UserList'
import Deportes from './admin/Deportes'
import DeportesDetail from './admin/DeportesDetail'
import DeportesForm from './admin/DeportesForm'
import Registro from '../components'
import LocalizacionesDetail from './admin/LocalizacionesDetail'
import Mapa from './admin/Mapa'
import Calendar from './user/Calendar'
import FutbolForm from './user/FutbolForm'
import TennisForm from './user/TennisForm'
import FutbolResult from './user/FutbolResult'
import TennisResult from './user/TennisResult'
import ValorationGame from './user/ValorationGame'
import Recomendations from './user/Recomendations'



export {Recomendations,TennisResult,TennisForm,Calendar,ValorationGame,FutbolResult,Mapa,FutbolForm,Weather,UserDetail,GameDetail, GameList,Game,GameUser,LocalizacionesDetail,UserList,DeportesDetail,Deportes,DeportesForm,Registro, GameCreate}